### ISSUE TITLE
Design: Create designs for the Product component 

### ISSUE THREAD

**Issue by Lovelyfin00** [purnima143/Pluto-UI#33]
## Issue summary

There is currently no design for the Product component and in order for the project to have a uniform styleguide, a design has to be created for each of the components.

## Proposed fix

Create a design for the Product component using the colors of the project which are already given on the README. 

## Tasks

- [ ] Product card
- [ ] Product list/grid view
- [ ] Product carousel/slider
- [ ] Product details page

After you start working on the issue, i.e designing, drop a link to the figma page here and give me alongside @AdityaSingh-02 and @purnima143 edit access

**Comment by aasthaaaa7** [comment]
hey,i'd like to work on this issue

**Comment by bhoomikhurana** [comment]
Has this work been done yet?I would like to take up this issue and apply my skills of UI and frontend dev into it

**Comment by Lovelyfin00** [comment]
Yes it's being worked on

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue.@Lovelyfin00
